/* Generated by tools/vmc.py: ids for vm/native.c (-1: not in the game). */
#ifndef GEN_NATIVE_H
#define GEN_NATIVE_H

#define IV_vtext 918
#define IV_myx 920
#define IV_myy 921
#define IV_writingx 131
#define IV_writingy 132
#define IV_writingxend 479
#define IV_vspacing 919
#define IV_stringpos 127
#define IV_originalstring 126
#define IV_mycolor 521
#define IV_halt 130
#define IV_stringno 133
#define IV_mystring 136
#define IV_textspeed 137
#define IV_myfont 922
#define IV_shake 342
#define IV_spacing 925
#define IV_htextscale 923
#define IV_vtextscale 924
#define IV_dogcheck 3729
#define GV_language 31
#define GV_typer 1
#define GV_flag 23
#define GV_faceemotion 45
#define GV_facechoice 44
#define GV_facechange 70
#define GV_currentroom 24
#define GV_entrance 49
#define GV_interact 46
#define GV_facing 51
#define FONT_fnt_comicsans 8
#define FONT_fnt_papyrus 9
#define CODE_gml_Object_obj_base_writer_Draw_0 825
#define CODE_gml_Script_SCR_TEXTTYPE 6045
#define CODE_gml_Script_scr_replace_buttons_pc 6217
#define CODE_gml_Script_scr_save 6222
#define CODE_gml_Script_scr_dogcheck 6129
#define PARTICLE_OBJECTS 115, 192, 193, 194, 195, 486, 1508
#define OBJ_obj_battler 143

#endif
