#!/usr/bin/env python3
"""Tables for vm/gmmath.c (fast trigonometry, the same on the Mac and the
calculator): writes vm/gmmath_tab.h."""
import math
from pathlib import Path

sin_tab = [round(math.sin(i * math.pi / 2048) * (1 << 23)) for i in range(1025)]
atan_tab = [round(math.degrees(math.atan(i / 1024)) * (1 << 16)) for i in range(1025)]


def arr(name, vals):
    rows = [", ".join(str(v) for v in vals[i:i + 8]) for i in range(0, len(vals), 8)]
    return f"static const uint24_t {name}[{len(vals)}] = {{\n    " + ",\n    ".join(rows) + "\n};\n"


out = Path(__file__).resolve().parent.parent / "vm" / "gmmath_tab.h"
out.write_text("/* generated by tools/gen_gmmath.py */\n"
               "/* sin(i * pi / 2048) in 1.23 fixed point */\n" + arr("sin_tab", sin_tab) +
               "/* atan(i / 1024) in degrees, 8.16 fixed point */\n" + arr("atan_tab", atan_tab))
