/* Generated by tools/convert_assets.py from data.win (room_area1). */
#ifndef AREA1_DATA_H
#define AREA1_DATA_H

#define AREA1_W 680
#define AREA1_H 260
#define AREA1_TILES_W 35 /* including the padding */
#define AREA1_TILES_H 14
#define AREA1_START_X 140
#define AREA1_START_Y 120
#define AREA1_DOOR_X 610 /* obj_doorA, 20x20 */
#define AREA1_DOOR_Y 140
#define SPRITE_TRANSPARENT 14

static uint8_t area1_tilemap[] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 7, 8, 9, 0, 0,
    0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 13, 14, 0, 0,
    0, 3, 3, 15, 16, 17, 18, 19, 20, 21, 22, 23, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 25, 26, 0, 0,
    0, 3, 3, 27, 28, 29, 30, 31, 32, 33, 34, 35, 3, 3, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 38, 39, 40, 41, 0, 0,
    0, 42, 3, 43, 44, 45, 46, 47, 48, 49, 50, 51, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0,
    0, 52, 53, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 54, 0, 0,
    0, 0, 52, 55, 3, 3, 3, 3, 3, 3, 3, 54, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 52, 55, 3, 3, 3, 3, 3, 54, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

static const wall_t area1_walls[] = {
    {WALL_SOLID, 660, 60, 20, 8000}, /* obj_solidtall */
    {WALL_SOLID, 0, 56, 20, 8000}, /* obj_solidtall */
    {WALL_SUR, 240, 60, 20, 20}, /* obj_sur */
    {WALL_SUL, 40, 60, 20, 20}, /* obj_sul */
    {WALL_SUR, 280, 140, 20, 20}, /* obj_sur */
    {WALL_SOLID, 280, 120, 20, 20}, /* obj_solidsmall */
    {WALL_SOLID, 280, 100, 20, 20}, /* obj_solidsmall */
    {WALL_SDR, 240, 200, 20, 20}, /* obj_sdr */
    {WALL_SDR, 220, 220, 20, 20}, /* obj_sdr */
    {WALL_SDL, 40, 200, 20, 20}, /* obj_sdl */
    {WALL_SDL, 20, 180, 20, 20}, /* obj_sdl */
    {WALL_SDL, 60, 220, 20, 20}, /* obj_sdl */
    {WALL_SOLID, 300, 140, 20, 20}, /* obj_solidsmall */
    {WALL_SOLID, 280, 80, 20, 20}, /* obj_solidsmall */
    {WALL_SOLID, 0, 240, 8000, 20}, /* obj_solidlong */
    {WALL_SOLID, 60, 40, 8000, 20}, /* obj_solidlong */
    {WALL_SOLID, 260, 200, 8000, 20}, /* obj_solidlong */
    {WALL_SOLID, 320, 140, 8000, 20}, /* obj_solidlong */
    {WALL_SOLID, 20, 60, 20, 20}, /* obj_solidsmall */
    {WALL_SOLID, 260, 60, 20, 20}, /* obj_solidsmall */
};

/* Precise masks of the diagonal walls: 20 rows of 3 bytes, MSB first. */
static const uint8_t mask_sdr[60] = {
    0x00, 0x00, 0x10, 0x00, 0x00, 0x30, 0x00, 0x00, 0x70, 0x00, 0x00, 0xf0,
    0x00, 0x01, 0xf0, 0x00, 0x03, 0xf0, 0x00, 0x07, 0xf0, 0x00, 0x0f, 0xf0,
    0x00, 0x1f, 0xf0, 0x00, 0x3f, 0xf0, 0x00, 0x7f, 0xf0, 0x00, 0xff, 0xf0,
    0x01, 0xff, 0xf0, 0x03, 0xff, 0xf0, 0x07, 0xff, 0xf0, 0x0f, 0xff, 0xf0,
    0x1f, 0xff, 0xf0, 0x3f, 0xff, 0xf0, 0x7f, 0xff, 0xf0, 0xff, 0xff, 0xf0,
};
static const uint8_t mask_sdl[60] = {
    0x80, 0x00, 0x00, 0xc0, 0x00, 0x00, 0xe0, 0x00, 0x00, 0xf0, 0x00, 0x00,
    0xf8, 0x00, 0x00, 0xfc, 0x00, 0x00, 0xfe, 0x00, 0x00, 0xff, 0x00, 0x00,
    0xff, 0x80, 0x00, 0xff, 0xc0, 0x00, 0xff, 0xe0, 0x00, 0xff, 0xf0, 0x00,
    0xff, 0xf8, 0x00, 0xff, 0xfc, 0x00, 0xff, 0xfe, 0x00, 0xff, 0xff, 0x00,
    0xff, 0xff, 0x80, 0xff, 0xff, 0xc0, 0xff, 0xff, 0xe0, 0xff, 0xff, 0xf0,
};
static const uint8_t mask_sur[60] = {
    0xff, 0xff, 0xf0, 0x7f, 0xff, 0xf0, 0x3f, 0xff, 0xf0, 0x1f, 0xff, 0xf0,
    0x0f, 0xff, 0xf0, 0x07, 0xff, 0xf0, 0x03, 0xff, 0xf0, 0x01, 0xff, 0xf0,
    0x00, 0xff, 0xf0, 0x00, 0x7f, 0xf0, 0x00, 0x3f, 0xf0, 0x00, 0x1f, 0xf0,
    0x00, 0x0f, 0xf0, 0x00, 0x07, 0xf0, 0x00, 0x03, 0xf0, 0x00, 0x01, 0xf0,
    0x00, 0x00, 0xf0, 0x00, 0x00, 0x70, 0x00, 0x00, 0x30, 0x00, 0x00, 0x10,
};
static const uint8_t mask_sul[60] = {
    0xff, 0xff, 0xf0, 0xff, 0xff, 0xe0, 0xff, 0xff, 0xc0, 0xff, 0xff, 0x80,
    0xff, 0xff, 0x00, 0xff, 0xfe, 0x00, 0xff, 0xfc, 0x00, 0xff, 0xf8, 0x00,
    0xff, 0xf0, 0x00, 0xff, 0xe0, 0x00, 0xff, 0xc0, 0x00, 0xff, 0x80, 0x00,
    0xff, 0x00, 0x00, 0xfe, 0x00, 0x00, 0xfc, 0x00, 0x00, 0xf8, 0x00, 0x00,
    0xf0, 0x00, 0x00, 0xe0, 0x00, 0x00, 0xc0, 0x00, 0x00, 0x80, 0x00, 0x00,
};

#endif
