/* Generated by tools/convert_assets.py from data.win (textdata_en). */
#ifndef INTRO_DATA_H
#define INTRO_DATA_H

#define LOGO_X 24
#define LOGO_Y 109

static const char *const intro_msg[] = {
    "Long ago^1, two races&ruled over Earth^1:&HUMANS and MONSTERS^6. \\E1 ^1 %",
    "One day^1, war broke&out between the two&races^6. \\E0 ^1 %",
    "After a long battle^1,&the humans were&victorious^6. \\E1 ^1 %",
    "They sealed the monsters&underground with a magic&spell^6. \\E0 ^1 %",
    "Many years later^2.^2.^5.  \\E1 ^1 %",
    "      MT. EBOTT&         201X^9 \\E0 %",
    "Legends say that those&who climb the mountain&never return^5.^3 \\E1 %",
    " \\E1 %",
    " ^9 ^5 \\E0 %",
    " ^9 ^5 ^2 \\E1 %",
    " ^9 ^5 ^2 \\E2 %",
    " ^9 ^9 ^9 ^9 ^9 ^9 \\E2 %%",
    " ^9 ^9 ^9 ^9 ^9  \\E0 %%",
    " ^9 ^9 ^9 ^9 ^9 ^9 \\E0 %",
    " %%",
};

#define STR_instructions_title " --- Instruction ---"
#define STR_instructions_confirm_label "Confirm"
#define STR_instructions_cancel_label "Cancel"
#define STR_instructions_menu_label "Menu (In-game)"
#define STR_instructions_quit_label "Quit"
#define STR_instructions_hp0 "When HP is 0, you lose."
#define STR_instructions_begin "Begin Game"
#define STR_settings_name "Settings"
#define STR_name_entry_title "Name the fallen human."
#define STR_name_entry_quit "Quit"
#define STR_name_entry_backspace "Backspace"
#define STR_name_entry_done "Done"
#define STR_name_entry_confirm "Is this name correct?"
#define STR_name_entry_missing "You must choose a name."
#define STR_name_entry_hardmode "WARNING: This name will#make your life hell.#Proceed anyway?"
#define STR_name_entry_goback "Go back"
#define STR_yes "Yes"
#define STR_no "No"

/* Names with their own reaction on the "Is this name correct?" screen.
   allow = 0 means the name is refused. */
typedef struct { const char *name; uint8_t allow; const char *msg; } special_name_t;
static const special_name_t special_names[] = {
    {"aaaaaa", 1, "Not very creative...?"},
    {"asgore", 0, "You cannot."},
    {"toriel", 0, "I think you should#think of your own#name, my child."},
    {"sans", 0, "nope."},
    {"undyne", 0, "Get your OWN name!"},
    {"flowey", 0, "I already CHOSE#that name."},
    {"chara", 1, "The true name."},
    {"alphys", 0, "D-don't do that."},
    {"alphy", 1, "Uh... OK?"},
    {"papyru", 1, "I'LL ALLOW IT!!!!"},
    {"napsta", 1, "...........#(They're powerless to#stop you.)"},
    {"blooky", 1, "...........#(They're powerless to#stop you.)"},
    {"murder", 1, "That's a little on-#the nose, isn't it...?"},
    {"mercy", 1, "That's a little on-#the nose, isn't it...?"},
    {"asriel", 0, "..."},
    {"catty", 1, "Bratty! Bratty!#That's MY name!"},
    {"bratty", 1, "Like, OK I guess."},
    {"mtt", 1, "OOOOH!!! ARE YOU#PROMOTING MY BRAND?"},
    {"metta", 1, "OOOOH!!! ARE YOU#PROMOTING MY BRAND?"},
    {"mett", 1, "OOOOH!!! ARE YOU#PROMOTING MY BRAND?"},
    {"gerson", 1, "Wah ha ha! Why not?"},
    {"shyren", 1, "...?"},
    {"aaron", 1, "Is this name correct? ; )"},
    {"temmie", 1, "hOI!"},
    {"woshua", 1, "Clean name."},
    {"jerry", 1, "Jerry."},
    {"bpants", 1, "You are really scraping the#bottom of the barrel."},
};

#endif
